// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RUsF6OHOmUM_3Vb4noFSSfw7ghnppwk',
    appId: '1:993759657648:web:534793bf25f1fb01330575',
    messagingSenderId: '993759657648',
    projectId: 'dotted-element-273213',
    authDomain: 'dotted-element-273213.firebaseapp.com',
    storageBucket: 'dotted-element-273213.firebasestorage.app',
    measurementId: 'G-HHGRKVLLNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-3F7EkxUaIedwOeqBoWZs-Vw7GAFh8Y',
    appId: '1:993759657648:android:bbdad022086b9956330575',
    messagingSenderId: '993759657648',
    projectId: 'dotted-element-273213',
    storageBucket: 'dotted-element-273213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtWBlbCF1wAsSQtefAWaxWTCSF3buaB0',
    appId: '1:993759657648:ios:37bc6ed85992dd04330575',
    messagingSenderId: '993759657648',
    projectId: 'dotted-element-273213',
    storageBucket: 'dotted-element-273213.firebasestorage.app',
    iosBundleId: 'com.avroy.locMate',
  );
}
